# djLint configuration

[tool.djlint]
profile = "django"
use_gitignore = true
exclude = ".github,docs,hilfe,linting,logs,node_modules,static,uploads,vendor"
ignore = "H006,T003"
ignore_case = true


# Ruff configuration

[tool.ruff]
exclude = [
  ".github",
  "docs",
  "hilfe",
  "linting",
  "logs",
  "node_modules",
  "static",
  "uploads",
  "vendor",
  "*/migrations/*"
]
line-length = 99
indent-width = 2

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["F403", "F405"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"datenwerft/__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = false
docstring-code-line-length = "dynamic"
