# djLint configuration

[tool.djlint]
profile = "django"
use_gitignore = true
exclude = ".github,docs,hilfe,linting,logs,node_modules,static,uploads,vendor"
ignore = "H006,T003"
ignore_case = true


# Ruff configuration

[tool.ruff]
exclude = [
  ".github",
  "docs",
  "hilfe",
  "linting",
  "logs",
  "node_modules",
  "static",
  "uploads",
  "vendor",
  "*/migrations/*"
]
line-length = 99
indent-width = 2
target-version = "py312"

[tool.ruff.lint]
ignore = ["DJ001", "DJ012", "F403", "F405"]
select = [
  # default
  "E",      # pycodestyle errors
  "F",      # flake8 errors
  # extra
  "A",      # built-in shadowing
  "DJ",     # flake8 django
  "LOG",    # flake8 logging
  "PIE",    # flake8 pie
  "T10",    # flake8 print
  "TCH",    # flake8 type-checking
  "W",      # pycodestyle warnings
  "YTT"    # wrong usage of sys.info
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"datenwerft/__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
